openapi: 3.0.0
info:
  version: 1.0.0
  title: test
servers:
  - url: 'http://localhost:3000/api'
paths:
  /prefectures:
    get:
      operationId: fetch-prefectures
      description: fetch prefecture list
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      required:
                        - code
                        - name
                      properties:
                        code:
                          type: string
                        name:
                          type: string
              examples:
                base:
                  value:
                    - code: '01'
                      name: '北海道'
                    - code: '02'
                      name: '青森県'
  /contacts:
    post:
      operationId: create-contact
      description: create contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: create contact request
              type: object
              required:
                - category
                - name
                - email
                - address
                - detail
              properties:
                category:
                  type: string
                name:
                  type: string
                email:
                  type: string
                address:
                  type: object
                  required:
                    - prefecture_code
                    - city
                  properties:
                    prefecture_code:
                      type: string
                    city:
                      type: string
                    detail:
                      type: string
                detail:
                  type: string
      responses:
        '201':
          description: 'success'
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              examples:
                base:
                  value:
                    message: 'お問い合わせが完了しました'
        '400':
          description: 'invalid request'
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
              examples:
                base:
                  value:
                    message: 'リクエストが不正です'
